= The Tree
:published_at: 2015-08-02
:hp-tags: Short Story, Writing,

There was a tree, and whoever planted him did a damn good job. However, this had to be a long time ago because of the tree being pretty big but surprisingly, the tree wasn’t so high as you then might expect. When it was planted, there was probably nothing around, whereas it is now the center of a little market square in a little, but really beautiful village somewhere in the nowhere. Furthermore, if the tree would have been a person all the time, it would have experienced a lot pretty sure. Whether the village being just a village and little now, it was on a very important trade route in the past. Therefore, you would have said that it was big back then. It just didn’t grow with the trade route losing its importance over time. Anyhow, there happened so much at this tree that a human brain wouldn’t be enough to remember it.

How it really was will remain unclear, but it’s more likely that this old tree was even there before the first crossing near him due to all there has begun with just a little, unpaved crossing. It should be clear that the city was important on the trade route because of its crossing with another route, isn’t it? Well, when there was no route at all, some nomads passed the place. They didn’t just travel as usual, they were searching for a better place to settle. All was dusty and dead from where they came, so they tried to be the architects of their own future. They decided to make a stop at the tree when they passed the place. However, this was pretty mandatory because one of the of women from the nomads was awaiting a child and it should be born this night. So when the dawn began, the contractions started as well. Then, already deep in the night, after hours of pain, the child was finally born and it was a beautiful girl. When the new mother looked at the baby holding it in her hands, as it lay there silently and sleeping, she made a decision. She talked with their elders, the young mother was convinced about the birth at this place being a sign and that all of them should settle here. Therefore, the elders asked the rest of the group and the opinion was divided, the most thought of it as a bright idea and were pretty willed to stay here, but some had other plans in their minds. Finally, as this little group couldn’t accept the decision of the majority, they decided to go ahead without the rest. So, they left each other. It’s discussable if this was a good decision or not. The group who left found and settled down in Canaan, while the others had a good and fulfilling life near the tree till they died. But you have to mention that the successor of the bigger group just died completely from a disease some decades later while the progeny of the Canaan-settlers still exists.

Furthermore, when there was a road already while the second to make a crossing out of it was on the way to be built, the first crime there happened. The Victim was an old man who was traveling together with his son. They were traders with the next bigger city as their destination to make some money. They weren’t trading expensive stuff as jewelry or gems, but they had some kinds of the first tools with them. All of them were pretty qualitative, at least at that time for the region they were currently. However, now there were only some little huts in the near range of the tree and the road, inhabited by skinny men and women. They were pretty poor because of the region’s worst land and dry climate, but wouldn’t move on because the too long journey they definitely wouldn’t survive in their condition. Therefore, they always saw an opportunity in strangers, especially rich-looking traders. Well, when the father and his son passed the area, the last sunbeams disappeared unfortunately behind the horizon. Both didn’t know the habits of the here living folk as they always traveled to cities in the south for trading instead of going west as this time. So they had to rest here through the night. They were searching for some dry wood but didn’t find any, it definitely would have been dry enough. Furthermore, both refused to kill the lonely tree for the wood, also because they would have to use the tools they wanted to trade. So the local folk came out in the darkest night when father and son already slept deeply. They were silent, none of them said a word while sneaking towards them. Standing above them looking down, one of them then took a big scimitar. It was looking old and already rusting, plus it was surprising that these people had such a weapon, even if in bad condition. However, the man holds it high into the air with both hands, pointing to the tip of it towards the father. Then, with a deep, horrifying cry, he rammed the scimitar into the body and the loving father was immediately dead. The man did a pretty good job from his point of view, but he forgot about the son who was wakened up by the cry and was now looking at his father being terrified. When the man mentioned his fault he began to grin and turned to the son, with the scimitar in his hands and the will in his eyes to kill the young man. The other people were standing a little bit aside, letting the man kill both and just watching him. Therefore, they couldn’t help when the boy reacted pretty fast by getting his bag and running away. In addition, none of them was able to follow him as none had the energy for it. Remember, they had less to eat and therefore neither the muscles nor the energy for it.

In the following years, the second road was finished and the crossing was finally developed. For the next centuries, nothing important happened anymore. But something very typical and usual in the region took place at the crossing several times. It was trading, contracting, but fighting as well. A little description how this usually occurred. Both parties normally arrived from the both sides of the same road, aiming to confront each other at the crossing. Then, they made their point clear, sometimes in a maybe rude way, and began the real cause of the meeting, either fighting, contracting or trading. Trading was normally pretty fast over, but the other two actions may take some more time. However, no matter of the actual case, both sides were often a bunch of people, whereas the most of them just acted as witnesses to eliminate the possibility of lying. This came up after a lot of cases of traders claiming that the things were stolen by the other involved trader instead of being traded for something else. Furthermore, the usual ending of such meetings is interesting to know. Well, if both are still alive at the end, so it wasn’t a fight till death, they normally give each other a handshake and sometimes also a friendly but not a lovely hug. Then, both parties turned around in the same moment and they walked the road back they came from. In a lot of cases, there was at least one of each group looking back to foreclose being tricked by the other party. And this is how negotiating and solving problems worked in the old days!

But life goes on and some time later, another group got the idea of settling near the tree. However, centuries passed and the humanity developed itself pretty much. Thus, great houses out of clay were built instead of simple huts. An administration was established and, around our already old and big tree, the marketplace was set. This led to the village growing rapidly and flourishing well. It not even needed two decades to make the village a city and an important center of trading. Anyway, problems are everywhere and they also were there in this settlement back then. It was the administration which struggled with inventing taxes that are accepted by the local population as well as by the folk of traveling traders. And this was pretty difficult. The main problem was a missing understanding of reasons for paying the taxes. As there was no money available, there also was no security managed by the city for their citizens. Nowadays, the following disaster would be pretty obvious but not in that far away past. Long story short, a lot of thieves saw potential in the city. Furthermore, these weren’t just pickpockets, more like crucial assassins. One of them planned to rob a man who got rich trough the trading. It was the deepest night when he neared the village. However, it was easy to get in. There were neither a town wall nor watchmen keeping an eye on the roads because none paid taxes for one of both as well as none did or paid it voluntarily, respectively. Everyone was already sleeping except the thief who sneaked only trough side streets and backyards he climbed in while being in attention. The journey was long from the outer city to the victim’s house due to the victim not only being one of the richest inhabitants, but also one of the first settlers, he built his house just next to our old tree, located directly at the marketplace. Ridiculously, the “high society” of the little city already developed a sense for being snobbish but not for safety or security yet. Thus, if they were robbed, they cautiously kept it as a secret for sure. This explains why the houses weren’t guarded too and why it was obviously easy for the thief to get into the house. However, he was still young and hasn’t very well experience in robbing. As dark as it was, he stumbled over the carpet, just after entering the building. This surely woke up the house owner, who rushed down to the entering hall with only a torch in his hand. As the thief was a crucial assassin, he attacked the surprised man with a dagger. But the owner could dodge the attack a bit, so only his arm got hurt. Anyway, the pain he felt led him to cry out pretty loud. This now also woke up the wife of the rich man who was unknown to the thief. Inexperienced as he was, he just mentioned the man himself as well as his wealth. Well, coming back to the entering hall. The thief was astonished by the cry and didn’t act in any way while the anger has grown in the victim. Hence, he slammed him down and tried to hit him with his torch, a fight began. Then, the on the floor laid thief stabbed the owner with the dagger and got his right leg. This time, the pain forced him on the ground as well, he felt into a corner of the room. The thief now stood up being fine and began to kick the man who wasn’t able to move anymore into his side. In the end, he wanted to finish him by stabbing the dagger into the house owners heart. He already hauled off, but suddenly he lost consciousness, falling on the floor. It was his wife who saved the rich man by sneaking behind the thief and bashing a chair onto his head. As his wife wasn’t a rich man's daughter, she insisted in going to the public and introducing taxes for town walls and night watchmen. As our rich man didn’t want a wife being crazy in the local opinion, he helped her and with his reputation and influence, all of the above things were invented as well as customs to get the traders pay for the safety as well. The first lobbying of history happened.

Over the years, the story got a well-told tale but didn’t refuse the people from paying the taxes well-behaved. The city, therefore, got bigger and bigger and pretty rich and our tree finally reached his maximums size, stopped growing at all. However, they had one significant problem: pollution. It wasn’t a problem of trash laying on the streets which could be solved be employing cleaners, more a problem of every water sources begin polluted by feces, as it was usual during medieval times. The best solution the administration could think off was building a canal system trough the city so filtering was possible to at least a decent level. Don’t ask me why, but the administration also saw the only way to build the system by cutting the tree down, as they planned to build an open one directly trough the marketplace where the tree is standing. This was the first critical event for the tree, his murder was under planning. However, the authorities of the plan didn’t count on the local inhabitants who grown up by playing under exactly this tree and remembering all the happy hours of their childhoods when looking at it. When the authorities announced the tree’s killing which was pretty close before the date, by the way, some of the villagers got a revolutionary idea. It came into their minds to just say the administration their opinion and get what they want by being the majority, pretty similar to action groups of nowadays. Well, for achieving their aim they had to get the majority for real. The consequence is obvious, they began to talk with other citizens, tried to persuade and convince them to help them to prevent the tree’s chopping. Some of them disagreed, particularly the ones who suffered most from the water pollution or at least wanted it to end, but the most was willed to support the little group who now already went a large organization. Therefore, all of them went to the tree on the date of the cutting together. The mayor and his administration already was there and looked shocked by the arriving masses of people walking trough the streets on the marketplace. When the complete crowd was standing before the local authorities, one older thick lady went forward. She looked as she already born three or more children on her own and was chosen as the speaker of the organization. She explained to them how important the tree is for the people living in the town and that the present mass of people could count as an evidence. The city administration rapidly agreed with her as they weren’t stupid and could see the actual problem they caused. Nonetheless, one question or problem, respectively, remained: how should the water pollution problem be solved otherwise? Obviously a tough one. However, the spokeswoman of the people wasn’t deeply impressed. Maybe because she was known to solving new problems with all the kids she raised up, anyway she already had several ideas. “We could make the water canal underground at least here, build it around the tree or jus keep the tree on an island” she said with a bored monotone voice as all this ideas she came up with just would be easy to think of and pretty obvious as well. What’s the best solution now could be discussed, but the administration just decided to keep the tree standing, build the canal surrounding it and connect to it by using little wood bridges as it is the cheapest method. So, the canals were built in the next few months, the water pollution issue was solved and the town did the first step out of medieval age into a brighter future. 

And Finally, the town and the tree got involved into war. Officially, it was part of a little kingdom which was friendly with all it neighbors since it existed. One reason was it importance for trading, being between a lot of realms in the west and a giant empire in the east which had a big and successful economy based on trading oriental goods, unknown in the west. Therefore, the western kingdoms obviously wanted to be friendly with the town’s kingdom for traveling to the eastern empire without an issue. However, sources of gold and gems were discovered in the kingdom the town laid in and the king was so excited that he didn’t keep it as a secret.